{{- if .Values.db.credentials.configureSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.db.credentials.secretName  }}"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
{{- if (eq .Values.db.credentials.passwordEncoding "plain") }}
  mysql-root-password:  {{ .Values.db.credentials.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.db.credentials.userPassword | b64enc | quote }}
{{- else }}
  mysql-root-password:  {{ .Values.db.credentials.rootPassword | quote }}
  mysql-password: {{ .Values.db.credentials.userPassword | quote }}
{{- end }}
{{- end }}
