apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  clusterIP: "None"
  ports:
  - name: {{ .Values.service.portName | default "mysql" | quote }}
    port: {{ .Values.service.port | default "3306" }}
    targetPort: {{ .Values.service.portName | default "mysql" | quote }}
    protocol: "TCP"
  selector:
    app: {{ .Values.app.name }}
